# Generated by Django 5.0.2 on 2024-04-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='profile',
            name='postcode',
            field=models.CharField(blank=True, max_length=50, verbose_name='Postcode'),
        ),
        migrations.AddField(
            model_name='profile',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address'),
        ),
    ]
